import 'dart:io';
import 'package:latlong2/latlong.dart' as ll;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PlotExporter {
  /// Generates a standard KML file containing corner placemarks and the boundary polygon
  static String generateKml(List<ll.LatLng> points, {String plotName = "Farm_Plot"}) {
    final buffer = StringBuffer();
    buffer.writeln('<?xml version="1.0" encoding="UTF-8"?>');
    buffer.writeln('<kml xmlns="http://www.opengis.net/kml/2.2">');
    buffer.writeln('  <Document>');
    buffer.writeln('    <name>$plotName</name>');

    // Add individual corner waypoint placemarks
    for (int i = 0; i < points.length; i++) {
      final pt = points[i];
      buffer.writeln('    <Placemark>');
      buffer.writeln('      <name>Corner ${i + 1}</name>');
      buffer.writeln('      <Point>');
      buffer.writeln('        <coordinates>${pt.longitude},${pt.latitude},0</coordinates>');
      buffer.writeln('      </Point>');
      buffer.writeln('    </Placemark>');
    }

    // Add closed polygon perimeter if 3 or more corners exist
    if (points.length >= 3) {
      buffer.writeln('    <Placemark>');
      buffer.writeln('      <name>$plotName Boundary</name>');
      buffer.writeln('      <Style>');
      buffer.writeln('        <LineStyle><color>ff0000ff</color><width>3</width></LineStyle>');
      buffer.writeln('        <PolyStyle><color>3f0000ff</color></PolyStyle>');
      buffer.writeln('      </Style>');
      buffer.writeln('      <Polygon>');
      buffer.writeln('        <outerBoundaryIs>');
      buffer.writeln('          <LinearRing>');
      buffer.writeln('            <coordinates>');

      for (final pt in points) {
        buffer.writeln('              ${pt.longitude},${pt.latitude},0');
      }
      // KML rings must explicitly close back to the first point
      buffer.writeln('              ${points.first.longitude},${points.first.latitude},0');

      buffer.writeln('            </coordinates>');
      buffer.writeln('          </LinearRing>');
      buffer.writeln('        </outerBoundaryIs>');
      buffer.writeln('      </Polygon>');
      buffer.writeln('    </Placemark>');
    }

    buffer.writeln('  </Document>');
    buffer.writeln('</kml>');
    return buffer.toString();
  }

  /// Generates a GPX 1.1 file containing waypoints and a track loop for Garmin GPS
  static String generateGpx(List<ll.LatLng> points, {String plotName = "Farm_Plot"}) {
    final buffer = StringBuffer();
    buffer.writeln('<?xml version="1.0" encoding="UTF-8"?>');
    buffer.writeln('<gpx version="1.1" creator="BotswanaPlotFinder" xmlns="http://www.topografix.com/GPX/1/1">');

    // Individual GPS Waypoints
    for (int i = 0; i < points.length; i++) {
      final pt = points[i];
      buffer.writeln('  <wpt lat="${pt.latitude}" lon="${pt.longitude}">');
      buffer.writeln('    <name>Corner_${i + 1}</name>');
      buffer.writeln('    <sym>Flag, Blue</sym>');
      buffer.writeln('  </wpt>');
    }

    // Track loop for Garmin navigation
    if (points.length >= 2) {
      buffer.writeln('  <trk>');
      buffer.writeln('    <name>$plotName Perimeter</name>');
      buffer.writeln('    <trkseg>');
      for (final pt in points) {
        buffer.writeln('      <trkpt lat="${pt.latitude}" lon="${pt.longitude}"/>');
      }
      if (points.length >= 3) {
        // Close loop
        buffer.writeln('      <trkpt lat="${points.first.latitude}" lon="${points.first.longitude}"/>');
      }
      buffer.writeln('    </trkseg>');
      buffer.writeln('  </trk>');
    }

    buffer.writeln('</gpx>');
    return buffer.toString();
  }

  /// Writes string content to app cache and triggers the Android share sheet
  static Future<void> shareFile({
    required String content,
    required String fileName,
    required String mimeType,
  }) async {
    final tempDir = await getTemporaryDirectory();
    final file = File('${tempDir.path}/$fileName');
    await file.writeAsString(content);

    await Share.shareXFiles(
      [XFile(file.path, mimeType: mimeType)],
      text: 'Plot boundaries generated by Botswana Plot Finder',
    );
  }
}
